# Generated by Django 4.1.3 on 2022-11-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="location_id",
            field=models.ManyToManyField(null=True, to="users.locations"),
        ),
    ]
