# Generated by Django 4.1.3 on 2022-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Пользователь", "Пользователь"),
                    ("Модератор", "Модератор"),
                    ("Администратор", "Администратор"),
                ],
                default="member",
                max_length=13,
            ),
        ),
    ]
